### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by Vatora** [RetroView/MetPrimeTools#31]
I've been following the work on hacking Metroid Prime sporadically for a while now. The work you guys have done so far is very impressive. However, I've run into a few issues when attempting to compile RetroView.

#### Dependency issue involving MathLib.hpp and SBoundingBox.hpp
`/RetroView/src/core/SBoundingBox.hpp` included by `/RetroView/src/core/GXCommon.hpp`
`/MathLib/MathLib.hpp` included by `/RetroView/src/core/SBoundingBox.hpp`
`/MathLib/SBoundingBox.hpp` included by `/MathLib/MathLib.hpp`

Trying to compile as is gives the error:
`/MetPrimeTools/MathLib/CFrustum.hpp:87: error: 'SBoundingBox' does not name a type`
`inline bool aabbFrustumTest(const SBoundingBox& aabb) const`

This can be fixed by removing /RetroView/src/core/SBoundingBox.hpp so that the version from MathLib is used.

#### Invalid initialization error on Win32 platforms
`/RetroView/src/core/src/CResourceManager.cpp:141: error: invalid initialization of reference of type 'std::string& {aka std::basic_string<char>&}' from expression of type 'const string {aka const std::basic_string<char>}'`
`Athena::utility::tolower(basepath);`

`Athena::utility::tolower(basepath);` exists at lines 124, 141, and 57.

My skills in programming are quite limited, so I could not easily solve this. However, commenting out these lines allowed the program to successfully compile and run without any obvious issues.

**Comment by Antidote** [comment]
Yeah, this is a known issue, I simply haven't gotten around to pushing the commit. I'll do that right now.

**Comment by Antidote** [comment]
Alright, I pushed the fix. Sorry about that.

**Comment by Vatora** [comment]
Not a problem. Just wanted to make sure the issue was known.
